name: Deployment workflow
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to the Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Log in to Server and Restarting Kubernetes
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DROPLET_IP }}
      #     username: ${{ secrets.DROPLET_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd /root/projects/admin
      #       ls
      #       kubectl delete -f k8s.yaml
      #       kubectl apply -f k8s.yaml

      - name: Telegram Notifications on Success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} successfully created commit ✅✅✅:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


      - name: Telegram Notifications on Failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} failed created commit ❌❌❌:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}